#!/bin/bash
# Filename:      |FILENAME|
# Purpose:       |CURSOR|
# Authors:       |AUTHOR| <|EMAIL|>
# Bug-Reports:   ---
# License:       This file is licensed under the GPL v2.
# Latest change: |DATETIME|
################################################################################

